### ISSUE TITLE
extra column in usecols_dtype

### ISSUE THREAD

**Issue by dgketchum** [DRI-WSWUP/cloud-free-scene-counts#9]
Looks like Pandas wasn't finding 'LANDSAT_SCENE_ID' in the csv.

I got this to run by commenting out scene_id_col:

    dtype_cols = {
        acq_date_col: object,
        browse_col: object,
        browse_url_col: object,
        col_number_col: object,
        col_category_col: object,
        cloud_col: float,
        data_type_col: object,
        product_id_col: object,
        # scene_id_col: object,
        sensor_col: object,
        time_col: object,
        wrs2_path_col: int,
        wrs2_row_col: int,
        # elevation_col: float,
        # azimuth_col: float,
    }

See traceback:

C:\cloud-free-scene-counts>python metadata_csv_filter.py -y 2015 -pr p041r027 -d

Filter/reducing Landsat Metadata CSV files
['acquisitionDate', 'browseAvailable', 'browseURL', 'CLOUD_COVER_LAND', 'COLLECTION_CATEGORY', 'COLLECTION_NUMBER', 'DATA_TYPE_L1', 'LANDSAT_PRODUCT_ID', 'LANDSAT_SCENE_ID', 'sensor', 'sceneStartTime', 'path', 'row']
  Paths: 41
  Rows: 27
  WRS2 Tiles: p041r027
LANDSAT_8_C1.csv
  Filtering by chunk
Traceback (most recent call last):
  File "metadata_csv_filter.py", line 495, in <module>
    years=args.years, months=args.months, conus_flag=args.conus)
  File "metadata_csv_filter.py", line 301, in main
    usecols=list(dtype_cols.keys()), dtype=dtype_cols)):
  File "C:\Users\justclickok\anaconda3\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\justclickok\anaconda3\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\justclickok\anaconda3\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\justclickok\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\justclickok\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1749, in __init__
    _validate_usecols_names(usecols, self.orig_names)
  File "C:\Users\justclickok\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1134, in _validate_usecols_names
    "columns expected but not found: {missing}".format(missing=missing)
ValueError: Usecols do not match columns, columns expected but not found: ['LANDSAT_SCENE_ID']

**Comment by dgketchum** [comment]
similar problem comes up in quicklook_download, though there are several columns missing
